"""
Week 3 Starter: RAG Pipeline over Research Papers using a Local LLM
----------------------------------------------------------------------
Architecture:
    papers/ (PDFs)
        → loaded with PyPDFLoader
        → split into chunks with RecursiveCharacterTextSplitter
        → embedded with nomic-embed-text (via Ollama, local)
        → stored in Chroma vector database (local file)
        → queried with cosine similarity search
        → retrieved chunks injected into prompt
        → answer generated by phi4-mini (or llama3.2:3b) via Ollama

Requirements:
    ollama pull nomic-embed-text
    ollama pull phi4-mini          (or llama3.2:3b)
    pip install langchain langchain-community langchain-ollama chromadb pypdf

Usage:
    # Index papers (first run — takes ~1 min):
    python week3/starter_code/rag_pipeline.py --index

    # Query (after indexing):
    python week3/starter_code/rag_pipeline.py "What methods are used for food segmentation?"

    # Rebuild the index from scratch:
    python week3/starter_code/rag_pipeline.py --reindex
"""

import argparse
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Configuration — adjust these to experiment
# ---------------------------------------------------------------------------
PAPERS_DIR = Path(__file__).parent.parent.parent / "papers"
CHROMA_DIR = Path(__file__).parent / "chroma_db"

EMBED_MODEL = "nomic-embed-text"   # pulled via: ollama pull nomic-embed-text
LLM_MODEL   = "phi4-mini"          # pulled via: ollama pull phi4-mini

CHUNK_SIZE    = 500    # tokens per chunk — try 200 or 1000 and compare
CHUNK_OVERLAP = 50     # overlap between adjacent chunks
TOP_K         = 4      # number of chunks to retrieve per query
# ---------------------------------------------------------------------------


def build_index():
    """Load PDFs, chunk them, embed, and store in Chroma."""
    from langchain_community.document_loaders import PyPDFLoader
    from langchain.text_splitter import RecursiveCharacterTextSplitter
    from langchain_community.vectorstores import Chroma
    from langchain_ollama import OllamaEmbeddings

    pdf_files = list(PAPERS_DIR.glob("*.pdf"))
    if not pdf_files:
        print(f"[ERROR] No PDF files found in {PAPERS_DIR}")
        print("Make sure you are running from the repo root directory.")
        sys.exit(1)

    print(f"[INFO] Found {len(pdf_files)} PDF(s) in {PAPERS_DIR}")

    # Step 1: Load all PDFs
    all_docs = []
    for pdf_path in pdf_files:
        print(f"  Loading: {pdf_path.name}")
        loader = PyPDFLoader(str(pdf_path))
        docs = loader.load()
        all_docs.extend(docs)

    print(f"[INFO] Total pages loaded: {len(all_docs)}")

    # Step 2: Split into chunks
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=CHUNK_SIZE,
        chunk_overlap=CHUNK_OVERLAP,
        separators=["\n\n", "\n", ". ", " ", ""],
    )
    chunks = splitter.split_documents(all_docs)
    print(f"[INFO] Total chunks created: {len(chunks)}")

    # Step 3: Embed and store (this calls Ollama locally)
    print(f"[INFO] Embedding with '{EMBED_MODEL}' (this may take a moment)...")
    embeddings = OllamaEmbeddings(model=EMBED_MODEL)
    vectorstore = Chroma.from_documents(
        documents=chunks,
        embedding=embeddings,
        persist_directory=str(CHROMA_DIR),
    )
    print(f"[INFO] Index saved to {CHROMA_DIR}")
    return vectorstore


def load_index():
    """Load an existing Chroma index from disk."""
    from langchain_community.vectorstores import Chroma
    from langchain_ollama import OllamaEmbeddings

    if not CHROMA_DIR.exists():
        print("[ERROR] No index found. Run with --index first.")
        sys.exit(1)

    embeddings = OllamaEmbeddings(model=EMBED_MODEL)
    vectorstore = Chroma(
        persist_directory=str(CHROMA_DIR),
        embedding_function=embeddings,
    )
    return vectorstore


def query(question: str, vectorstore):
    """Retrieve relevant chunks and generate an answer."""
    from langchain_ollama import OllamaLLM
    from langchain.prompts import PromptTemplate

    # Step 1: Retrieve relevant chunks
    retriever = vectorstore.as_retriever(search_kwargs={"k": TOP_K})
    docs = retriever.invoke(question)

    print(f"\n[Retrieved {len(docs)} chunks]")
    print("-" * 60)

    # Optional: show retrieved chunks so you can inspect retrieval quality
    for i, doc in enumerate(docs, 1):
        source = doc.metadata.get("source", "unknown")
        page   = doc.metadata.get("page", "?")
        print(f"  Chunk {i} — {Path(source).name}, page {page}")
        print(f"  {doc.page_content[:200].strip()}...")
        print()

    # Step 2: Build context string from retrieved chunks
    context = "\n\n---\n\n".join(
        f"[Source: {Path(doc.metadata.get('source', '')).name}, "
        f"page {doc.metadata.get('page', '?')}]\n{doc.page_content}"
        for doc in docs
    )

    # Step 3: Prompt the LLM
    prompt_template = PromptTemplate.from_template(
        """You are a research assistant. Use ONLY the context below to answer 
the question. If the answer is not in the context, say "I don't have enough 
information in the provided papers to answer this."

Context:
{context}

Question: {question}

Answer:"""
    )

    llm = OllamaLLM(model=LLM_MODEL, temperature=0.1)
    chain = prompt_template | llm

    print("=== Answer ===")
    answer = chain.invoke({"context": context, "question": question})
    print(answer)
    return answer


def main():
    parser = argparse.ArgumentParser(description="RAG pipeline over research papers")
    parser.add_argument("question", nargs="?", help="Question to ask the RAG system")
    parser.add_argument("--index",   action="store_true", help="Build the vector index")
    parser.add_argument("--reindex", action="store_true", help="Rebuild index from scratch")
    args = parser.parse_args()

    if args.reindex:
        import shutil
        if CHROMA_DIR.exists():
            shutil.rmtree(CHROMA_DIR)
            print(f"[INFO] Removed existing index at {CHROMA_DIR}")
        build_index()
        return

    if args.index:
        build_index()
        return

    if args.question:
        vectorstore = load_index()
        query(args.question, vectorstore)
        return

    parser.print_help()


if __name__ == "__main__":
    main()
